/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SoulBound__factory } from "./SoulBound__factory";
export { NftPass__factory } from "./NftPass__factory";
