/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SoulBound } from "./SoulBound";
export type { NftPass } from "./NftPass";
export * as factories from "./factories";
export { NftPass__factory } from "./factories/NftPass__factory";
export { SoulBound__factory } from "./factories/SoulBound__factory";
